# setup-env.ps1
# Creates the frontend .env file and optionally triggers a redeploy.
# Run from the repo root: .\scripts\setup-env.ps1

param(
    [string]$ApiUrl = ""
)

$ErrorActionPreference = "Stop"
$RepoRoot  = Split-Path $PSScriptRoot -Parent
$FrontendDir = Join-Path $RepoRoot "marketapp\frontend"
$EnvFile   = Join-Path $FrontendDir ".env"

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  WoW Market Tracker — Frontend .env Setup" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# ── Verify frontend dir exists ───────────────────────────────────────────────
if (-not (Test-Path $FrontendDir)) {
    Write-Host "[ERROR] Frontend directory not found: $FrontendDir" -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Frontend directory found" -ForegroundColor Green

# ── Get API URL ───────────────────────────────────────────────────────────────
if (-not $ApiUrl) {
    Write-Host ""
    Write-Host "Enter your deployed API worker URL." -ForegroundColor Yellow
    Write-Host "Example: https://wow-market-api.your-subdomain.workers.dev" -ForegroundColor DarkGray
    Write-Host ""
    $ApiUrl = Read-Host "API Worker URL"
}

$ApiUrl = $ApiUrl.TrimEnd("/")

if (-not $ApiUrl.StartsWith("https://")) {
    Write-Host "[ERROR] URL must start with https://" -ForegroundColor Red
    exit 1
}

$PublicApiBase = "$ApiUrl/api"
Write-Host ""
Write-Host "[INFO] PUBLIC_API_BASE will be set to: $PublicApiBase" -ForegroundColor DarkCyan

# ── Check existing .env ───────────────────────────────────────────────────────
if (Test-Path $EnvFile) {
    Write-Host ""
    Write-Host "[WARN] .env already exists at $EnvFile" -ForegroundColor Yellow
    $overwrite = Read-Host "Overwrite? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "[SKIP] Leaving existing .env unchanged." -ForegroundColor DarkGray
        exit 0
    }
}

# ── Write .env file ───────────────────────────────────────────────────────────
Write-Host ""
Write-Host "[INFO] Writing .env file..." -ForegroundColor DarkCyan
$envContent = @"
# WoW Market Tracker Frontend Environment
# Generated by setup-env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

PUBLIC_API_BASE=$PublicApiBase
"@

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Write-Host "[OK] Created: $EnvFile" -ForegroundColor Green

# ── Verify wrangler is available ─────────────────────────────────────────────
Write-Host ""
Write-Host "[INFO] Checking wrangler availability..." -ForegroundColor DarkCyan
$wranglerAvailable = $null
try {
    $wranglerAvailable = Get-Command wrangler -ErrorAction SilentlyContinue
} catch {}

if (-not $wranglerAvailable) {
    Write-Host "[WARN] wrangler not found in PATH. Skipping redeploy." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "To rebuild and redeploy the frontend manually:" -ForegroundColor Yellow
    Write-Host "  cd marketapp\frontend" -ForegroundColor DarkGray
    Write-Host "  npm run build" -ForegroundColor DarkGray
    Write-Host "  wrangler pages deploy dist --project-name wow-market-frontend" -ForegroundColor DarkGray
} else {
    Write-Host "[OK] wrangler found" -ForegroundColor Green
    Write-Host ""
    $redeploy = Read-Host "Rebuild and redeploy frontend to Cloudflare Pages now? (y/N)"
    if ($redeploy -eq "y" -or $redeploy -eq "Y") {
        Write-Host ""
        Write-Host "[INFO] Running npm run build..." -ForegroundColor DarkCyan
        Push-Location $FrontendDir
        try {
            npm run build
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[ERROR] Build failed." -ForegroundColor Red
                exit 1
            }
            Write-Host "[OK] Build complete" -ForegroundColor Green

            Write-Host ""
            Write-Host "[INFO] Deploying to Cloudflare Pages..." -ForegroundColor DarkCyan
            wrangler pages deploy dist --project-name wow-market-frontend
            if ($LASTEXITCODE -ne 0) {
                Write-Host "[ERROR] Deploy failed." -ForegroundColor Red
                exit 1
            }
            Write-Host "[OK] Frontend redeployed" -ForegroundColor Green
        } finally {
            Pop-Location
        }
    } else {
        Write-Host "[SKIP] Skipping redeploy. Run manually when ready." -ForegroundColor DarkGray
    }
}

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  Done! .env is configured." -ForegroundColor Green
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
